#!/usr/bin/env bash

set -e

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

cd /var/www/html

if [ -f composer.json ] && [ ! -f vendor/autoload.php ]; then
    echo "Installing PHP dependencies with Composer..."

    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        COMPOSER_ALLOW_SUPERUSER=1 composer install --no-interaction --prefer-dist
    else
        gosu $WWWUSER env COMPOSER_ALLOW_SUPERUSER=1 composer install --no-interaction --prefer-dist
    fi
fi

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
