<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ $subject ?? 'CaseDex Notification' }}</title>
  </head>
  <body style="margin:0;padding:0;background:#f1f5f9;font-family:Segoe UI,Arial,sans-serif;color:#0f172a;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="padding:24px 12px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;background:#ffffff;border:1px solid #cbd5e1;border-radius:16px;overflow:hidden;">
            <tr>
              <td style="padding:20px 24px;border-bottom:1px solid #e2e8f0;background:#f8fafc;">
                <div style="font-size:12px;letter-spacing:0.24em;text-transform:uppercase;color:#64748b;font-weight:700;">Case workspace</div>
                <div style="font-size:22px;font-weight:700;color:#0f172a;margin-top:6px;">CaseDex</div>
              </td>
            </tr>
            <tr>
              <td style="padding:24px;line-height:1.7;font-size:15px;">
                @yield('content')
              </td>
            </tr>
            <tr>
              <td style="padding:16px 24px;border-top:1px solid #e2e8f0;background:#f8fafc;font-size:12px;color:#64748b;line-height:1.6;">
                CaseDex is a structured case workspace for legal professionals and law students.<br />
                This message was generated by your workspace notifications settings.
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
