<?php

return [
    'brand_kicker' => 'Case workspace',
    'footer_tagline' => 'CaseDex is a structured case workspace for legal professionals and law students.',
    'footer_reason' => 'This message was generated by your workspace notifications settings.',
    'hello' => 'Hello :name,',
    'label_case' => 'Case',
    'label_court' => 'Court',
    'label_case_number' => 'Case number',
    'label_added_by' => 'Added by',
    'label_hearing' => 'Hearing',
    'label_hearing_time' => 'Hearing time',
    'label_time' => 'Time',
    'label_ip' => 'IP address',
    'label_temp_password' => 'Temporary password',
    'value_tbd' => 'TBD',
    'value_pending' => 'Pending',
    'value_case' => 'Case',
    'value_team' => 'CaseDex team',

    'verify_subject' => 'Verify your CaseDex™ email',
    'verify_intro' => 'Please verify your email address to secure your CaseDex account.',
    'verify_button' => 'Verify email',
    'verify_outro' => 'If you did not create this account, you can ignore this message.',

    'reset_subject' => 'Reset your CaseDex™ password',
    'reset_intro' => 'We received a password reset request for your account.',
    'reset_button' => 'Reset password',
    'reset_outro' => 'If this was not you, ignore this email and your password will remain unchanged.',

    'password_changed_subject' => 'Your CaseDex™ password was updated',
    'password_changed_intro' => 'Your password was changed successfully.',
    'password_changed_outro' => 'If you did not perform this action, reset your password immediately.',

    'invite_subject' => 'You have been added to a CaseDex™ workspace',
    'invite_intro' => 'You were added to a workspace team.',
    'invite_button' => 'Sign in',
    'invite_outro' => 'After first login, update your password from profile settings.',

    'party_added_subject' => 'You have been added to a case',
    'party_added_intro' => 'You were added as a party on a case.',
    'party_added_outro' => 'If this is unexpected, contact your case team.',

    'hearing_reminder_subject' => 'Hearing reminder',
    'hearing_reminder_intro' => 'A hearing is scheduled for tomorrow.',
    'hearing_reminder_outro' => 'Review hearing notes and required next steps before session time.',

    'notification_subject_fallback' => 'CaseDex notification',
];
